# -*- coding: utf-8 -*-
"""
core_utils.subprocess_utils -- Self-Heal Subprocess Runner
===========================================================
Replaces 15+ duplicated patterns of:
    import subprocess
    subprocess.run(["python", module_name], cwd=str(WORKSPACE))

Usage:
    from core_utils.subprocess_utils import run_module, self_heal_or_skip
    
    # Run a backend module and raise if it fails
    run_module("fsi_mapper.py")
    
    # Self-heal: run generator if output file missing
    data = self_heal_or_skip("output.json", "generator.py")
    # Returns loaded JSON dict or None (if skipped)
"""

import sys
import subprocess
from pathlib import Path
from typing import Optional, Any, Dict, List


def _get_workspace() -> Path:
    return Path.cwd()


def _get_injected_env() -> Dict[str, str]:
    """Lazily import portable_env_injector and return an env dict with embedded runtime paths injected."""
    try:
        from core_utils.portable_env_injector import inject_env
        return inject_env()
    except ImportError:
        import os
        return dict(os.environ)


def run_module(
    module_name: str,
    args: Optional[List[str]] = None,
    capture: bool = True,
    timeout: Optional[int] = 120,
    raise_on_error: bool = False
) -> subprocess.CompletedProcess:
    """
    Run a Python module as a subprocess.

    Parameters
    ----------
    module_name : e.g., "fsi_mapper.py", "structural_homogenizer.py"
    args : additional CLI args
    capture : capture stdout/stderr
    timeout : max seconds
    raise_on_error : raise on non-zero exit code

    Returns
    -------
    subprocess.CompletedProcess
    """
    cmd = [sys.executable, module_name]
    if args:
        cmd.extend(args)

    workspace = _get_workspace()
    
    kwargs = {}
    if capture:
        kwargs["capture_output"] = True
        kwargs["text"] = True
    if timeout:
        kwargs["timeout"] = timeout

    # 동적 환경 변수 주입 (embedded runtime PATH)
    kwargs["env"] = _get_injected_env()

    result = subprocess.run(cmd, cwd=str(workspace), **kwargs)
    
    if raise_on_error and result.returncode != 0:
        err = result.stderr[-500:] if capture else f"exit code {result.returncode}"
        raise RuntimeError(f"Module {module_name} failed: {err}")
    
    return result


def self_heal_or_skip(
    data_path: str,
    generator_module: str,
    generator_args: Optional[List[str]] = None,
    load_json: bool = True
) -> Optional[Any]:
    """
    Check if data file exists. If not, run generator to create it.
    If still missing after generator, return None (skip).

    Parameters
    ----------
    data_path : path to expected output file
    generator_module : module to run if file missing
    generator_args : extra args for generator
    load_json : if True, load and return parsed JSON

    Returns
    -------
    Parsed JSON dict/list, or None if file doesn't exist
    """
    import json
    workspace = _get_workspace()
    target = workspace / data_path

    if not target.exists():
        print(f"  [SELF-HEAL] {data_path} missing. Running {generator_module}...")
        run_module(generator_module, args=generator_args)
    
    if not target.exists():
        print(f"  [SKIP] {data_path} not generated by {generator_module}.")
        return None
    
    if load_json:
        with open(target, "r", encoding="utf-8") as f:
            return json.load(f)
    return target


def run_openfoam(
    command: str,
    case_dir: str,
    bash_path: Optional[str] = None
) -> bool:
    """
    Run an OpenFOAM command via blueCFD bash (portable embedded runtime).

    Parameters
    ----------
    command : e.g., "blockMesh", "injectionFoam"
    case_dir : case directory path
    bash_path : path to bash.exe (auto-detect from embedded runtime if None)

    Returns
    -------
    True if command succeeded
    """
    import os
    workspace = _get_workspace()
    case_path = workspace / case_dir

    if bash_path is None:
        # 동적 경로 추적: embedded_runtime/bluecfd_core/msys64/usr/bin/bash.exe
        try:
            from core_utils.portable_env_injector import get_bash_path
            bash = get_bash_path()
            if not bash.exists():
                # Fallback to legacy hardcoded path
                bash = Path(r"d:\Program-Files\blueCFD-Core-2024\msys64\usr\bin\bash.exe")
        except ImportError:
            bash = Path(r"d:\Program-Files\blueCFD-Core-2024\msys64\usr\bin\bash.exe")
    else:
        bash = Path(bash_path)

    if not bash.exists():
        raise FileNotFoundError(f"bash.exe not found at {bash}")

    cwd_posix = str(case_path).replace('\\', '/').replace('D:', '/d').replace('d:', '/d')
    
    of_env = (
        'export WM_PROJECT=OpenFOAM && export WM_PROJECT_VERSION=12 && '
        f'cd "{cwd_posix}" && {command} 2>&1'
    )

    # 포터블 환경 변수 주입
    try:
        from core_utils.portable_env_injector import inject_env
        env = inject_env()
    except ImportError:
        env = None
    
    result = subprocess.run(
        [str(bash), '-c', of_env],
        cwd=str(case_path),
        capture_output=True,
        text=True,
        timeout=300,
        env=env
    )
    return result.returncode == 0


def run_with_status(module_name: str, args: Optional[List[str]] = None) -> Dict[str, Any]:
    """
    Run a module and return structured status dict.
    Used by system_auditor self-heal patterns.
    
    Returns {"ok": True, "stdout": "...", "stderr": "..."}
    """
    try:
        r = run_module(module_name, args=args, capture=True, timeout=60)
        return {
            "ok": r.returncode == 0,
            "stdout": r.stdout[-2000:] if r.stdout else "",
            "stderr": r.stderr[-500:] if r.stderr else "",
            "code": r.returncode
        }
    except Exception as e:
        return {
            "ok": False,
            "stdout": "",
            "stderr": str(e),
            "code": -1
        }